version: '2'
services:
  review:
    container_name: smart-review
    image: ghcr.io/lizec123/smart-review:latest
    ports: 
      - "6080:80"
    environment: 
      TZ: Asia/Shanghai
      GIN_MODE: release
    volumes: 
      - ./data:/app/data
  #   depends_on: 
  #     - redis
  # redis:
  #   container_name: smart-review-redis
  #   image: redis:6.2.5-alpine
  #   expose:
  #     - "6379"  
