version: '2'
services:
  backend:
    container_name: smart-review-backend
    build: 
      context: ./
      dockerfile: docker/backend/Dockerfile
    expose: 
      - 8792
    # TODO: 导出文件是否需要映射到Host
    volumes: 
      - ./data:/app/data
    environment: 
      TZ: Asia/Shanghai
    depends_on: 
      - mysql
      - redis
  redis:
    container_name: smart-review-redis
    image: redis:6.2.5-alpine
    expose:
      - 6379
  mysql:
    container_name: smart-review-mysql
    command: --default-authentication-plugin=mysql_native_password
    build: 
      context: ./
      dockerfile: docker/mysql/Dockerfile
    expose:
      - 3306
    volumes: 
      - ./data/mysql:/var/lib/mysql
  web:
    container_name: smart-review-web
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    ports: 
      - "6080:80"
    depends_on: 
      - backend
  