spring:
  application:
    name: SmartReview
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_review?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
server:
  port: 8792
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.lizec.smartreview.entity
  configuration:
    map-underscore-to-camel-case: true


---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    top.lizec.smartreview.mapper: TRACE

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8792


