spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: SmartReview
  datasource:
    url: jdbc:sqlite:data/SmartReview.db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始连接数量和最小连接数量可以减少初次访问时建立连接的时间
    druid:
      min-idle: 2
      initial-size: 2
      validationQuery: "SELECT 1"
  redis:
    jedis:
      pool:
        min-idle: 1
server:
  port: 8792
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.lizec.smartreview.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    top.lizec.smartreview.mapper: DEBUG
smart-review:
    init-review-hour: 0

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: SmartReview
  datasource:
    url: jdbc:sqlite:data/SmartReview.db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始连接数量和最小连接数量可以减少初次访问时建立连接的时间
    druid:
      min-idle: 2
      initial-size: 2
      validationQuery: "SELECT 1"
  redis:
    jedis:
      pool:
        min-idle: 1
server:
  port: 8792
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.lizec.smartreview.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: data/SmartReview.log
smart-review:
  init-review-hour: 12