spring:
  profiles:
    active: dev
  application:
    name: SmartReview
  redis:
    jedis:
      pool:
        min-idle: 1
server:
  port: 8792
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.lizec.smartreview.entity
  configuration:
    map-underscore-to-camel-case: true


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:data/SmartReview.db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始连接数量和最小连接数量可以减少初次访问时建立连接的时间
    druid:
      min-idle: 2
      initial-size: 2
      validationQuery: "SELECT 1"

logging:
  level:
    top.lizec.smartreview.mapper: TRACE

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:sqlite:data/SmartReview.db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始连接数量和最小连接数量可以减少初次访问时建立连接的时间
    druid:
      min-idle: 2
      initial-size: 2
      validationQuery: "SELECT 1"


